class Buff {
    int id;
    String name;
    int icon;
    String type;
    int conflict;
    String version;
    String kungfuLimit;
    int effectId;

    List<String> toList() {
        return [
            '$id',
            name,
            '$icon',
            type,
            '$conflict',
            version,
            kungfuLimit,
            '$effectId',
        ];
    }
}

class RawBuff {
    String id;
    String name;
    String useage;
    String kindType;
    String functionType;
    String representPos;
    String representId;
    String appendType;
    String detachType;
    String buffType;
    String level;
    String intensity;
    String isStackable;
    String maxStackNum;
    String count;
    String interval;
    String hide;
    String exclude;
    String save;
    String onStand;
    String onWalk;
    String onRun;
    String onJump;
    String onSwim;
    String onFloat;
    String onSit;
    String onKnockedDown;
    String onKnockedBack;
    String onKnockedOff;
    String onHalt;
    String onAutoFly;
    String onDeath;
    String onDash;
    String onPull;
    String onManaShield;
    String onFight;
    String onHorse;
    String onTerrain;
    String formationLeader;
    String scriptFile;
    String globalExclude;
    String uniqueTarget;
    String canCancel;
    String beginAttrib1;
    String beginValue1A;
    String beginValue1B;
    String beginAttrib2;
    String beginValue2A;
    String beginValue2B;
    String beginAttrib3;
    String beginValue3A;
    String beginValue3B;
    String beginAttrib4;
    String beginValue4A;
    String beginValue4B;
    String beginAttrib5;
    String beginValue5A;
    String beginValue5B;
    String beginAttrib6;
    String beginValue6A;
    String beginValue6B;
    String beginAttrib7;
    String beginValue7A;
    String beginValue7B;
    String beginAttrib8;
    String beginValue8A;
    String beginValue8B;
    String beginAttrib9;
    String beginValue9A;
    String beginValue9B;
    String beginAttrib10;
    String beginValue10A;
    String beginValue10B;
    String beginAttrib11;
    String beginValue11A;
    String beginValue11B;
    String beginAttrib12;
    String beginValue12A;
    String beginValue12B;
    String beginAttrib13;
    String beginValue13A;
    String beginValue13B;
    String beginAttrib14;
    String beginValue14A;
    String beginValue14B;
    String beginAttrib15;
    String beginValue15A;
    String beginValue15B;
    String activeAttrib1;
    String activeValue1A;
    String activeValue1B;
    String activeAttrib2;
    String activeValue2A;
    String activeValue2B;
    String endTimeAttrib1;
    String endTimeValue1A;
    String endTimeValue1B;
    String endTimeAttrib2;
    String endTimeValue2A;
    String endTimeValue2B;
    String isCountable;
    String decayType;
    String moveStateMask;
    String mapBanMask;
    String isOffLineClock;
    String canAccumulate;
    String srcDistance;
    String inSprint;
    String inParkour;
    String inFollow;
    String cancelByUseItem;
    String mapInvalidMask;
    String isCombatBuff;
    String minInterval;
    String clearUnderWater;
    String moveStateMask2;
    String shapeShiftInvalid;
    String maxInterval;
    String activeCoefficient;
    String canBeSteal;
    String needSync;
    String inBirdMove;
    String canTransfer;

    RawBuff.fromJson(Map<String, dynamic> json) {
        id = json['ID'];
        name = json['Name'];
        useage = json['Useage'];
        kindType = json['KindType'];
        functionType = json['FunctionType'];
        representPos = json['RepresentPos'];
        representId = json['RepresentID'];
        appendType = json['AppendType'];
        detachType = json['DetachType'];
        buffType = json['BuffType'];
        level = json['Level'];
        intensity = json['Intensity'];
        isStackable = json['IsStackable'];
        maxStackNum = json['MaxStackNum'];
        count = json['Count'];
        interval = json['Interval'];
        hide = json['Hide'];
        exclude = json['Exclude'];
        save = json['Save'];
        onStand = json['OnStand'];
        onWalk = json['OnWalk'];
        onRun = json['OnRun'];
        onJump = json['OnJump'];
        onSwim = json['OnSwim'];
        onFloat = json['OnFloat'];
        onSit = json['OnSit'];
        onKnockedDown = json['OnKnockedDown'];
        onKnockedBack = json['OnKnockedBack'];
        onKnockedOff = json['OnKnockedOff'];
        onHalt = json['OnHalt'];
        onAutoFly = json['OnAutoFly'];
        onDeath = json['OnDeath'];
        onDash = json['OnDash'];
        onPull = json['OnPull'];
        onManaShield = json['OnManaShield'];
        onFight = json['OnFight'];
        onHorse = json['OnHorse'];
        onTerrain = json['OnTerrain'];
        formationLeader = json['FormationLeader'];
        scriptFile = json['ScriptFile'];
        globalExclude = json['GlobalExclude'];
        uniqueTarget = json['UniqueTarget'];
        canCancel = json['CanCancel'];
        beginAttrib1 = json['BeginAttrib1'];
        beginValue1A = json['BeginValue1A'];
        beginValue1B = json['BeginValue1B'];
        beginAttrib2 = json['BeginAttrib2'];
        beginValue2A = json['BeginValue2A'];
        beginValue2B = json['BeginValue2B'];
        beginAttrib3 = json['BeginAttrib3'];
        beginValue3A = json['BeginValue3A'];
        beginValue3B = json['BeginValue3B'];
        beginAttrib4 = json['BeginAttrib4'];
        beginValue4A = json['BeginValue4A'];
        beginValue4B = json['BeginValue4B'];
        beginAttrib5 = json['BeginAttrib5'];
        beginValue5A = json['BeginValue5A'];
        beginValue5B = json['BeginValue5B'];
        beginAttrib6 = json['BeginAttrib6'];
        beginValue6A = json['BeginValue6A'];
        beginValue6B = json['BeginValue6B'];
        beginAttrib7 = json['BeginAttrib7'];
        beginValue7A = json['BeginValue7A'];
        beginValue7B = json['BeginValue7B'];
        beginAttrib8 = json['BeginAttrib8'];
        beginValue8A = json['BeginValue8A'];
        beginValue8B = json['BeginValue8B'];
        beginAttrib9 = json['BeginAttrib9'];
        beginValue9A = json['BeginValue9A'];
        beginValue9B = json['BeginValue9B'];
        beginAttrib10 = json['BeginAttrib10'];
        beginValue10A = json['BeginValue10A'];
        beginValue10B = json['BeginValue10B'];
        beginAttrib11 = json['BeginAttrib11'];
        beginValue11A = json['BeginValue11A'];
        beginValue11B = json['BeginValue11B'];
        beginAttrib12 = json['BeginAttrib12'];
        beginValue12A = json['BeginValue12A'];
        beginValue12B = json['BeginValue12B'];
        beginAttrib13 = json['BeginAttrib13'];
        beginValue13A = json['BeginValue13A'];
        beginValue13B = json['BeginValue13B'];
        beginAttrib14 = json['BeginAttrib14'];
        beginValue14A = json['BeginValue14A'];
        beginValue14B = json['BeginValue14B'];
        beginAttrib15 = json['BeginAttrib15'];
        beginValue15A = json['BeginValue15A'];
        beginValue15B = json['BeginValue15B'];
        activeAttrib1 = json['ActiveAttrib1'];
        activeValue1A = json['ActiveValue1A'];
        activeValue1B = json['ActiveValue1B'];
        activeAttrib2 = json['ActiveAttrib2'];
        activeValue2A = json['ActiveValue2A'];
        activeValue2B = json['ActiveValue2B'];
        endTimeAttrib1 = json['EndTimeAttrib1'];
        endTimeValue1A = json['EndTimeValue1A'];
        endTimeValue1B = json['EndTimeValue1B'];
        endTimeAttrib2 = json['EndTimeAttrib2'];
        endTimeValue2A = json['EndTimeValue2A'];
        endTimeValue2B = json['EndTimeValue2B'];
        isCountable = json['IsCountable'];
        decayType = json['DecayType'];
        moveStateMask = json['MoveStateMask'];
        mapBanMask = json['MapBanMask'];
        isOffLineClock = json['IsOffLineClock'];
        canAccumulate = json['CanAccumulate'];
        srcDistance = json['SrcDistance'];
        inSprint = json['InSprint'];
        inParkour = json['InParkour'];
        inFollow = json['InFollow'];
        cancelByUseItem = json['CancelByUseItem'];
        mapInvalidMask = json['MapInvalidMask'];
        isCombatBuff = json['IsCombatBuff'];
        minInterval = json['MinInterval'];
        clearUnderWater = json['ClearUnderWater'];
        moveStateMask2 = json['MoveStateMask2'];
        shapeShiftInvalid = json['ShapeShiftInvalid'];
        maxInterval = json['MaxInterval'];
        activeCoefficient = json['ActiveCoefficient'];
        canBeSteal = json['CanBeSteal'];
        needSync = json['NeedSync'];
        inBirdMove = json['InBirdMove'];
        canTransfer = json['CanTransfer'];
    }
}

class RawFormationInfo {
    String skillId;
    String name;
    String level3;
    String level4;
    String level5;
    String level6;

    RawFormationInfo.fromJson(Map<String, dynamic> json) {
        skillId = json['skillId'];
        name = json['name'];
        level3 = json['level3'];
        level4 = json['level4'];
        level5 = json['level5'];
        level6 = json['level6'];
    }
}
